## 라이브러리

In [7]:
import pandas as pd
import numpy as np
from scipy.stats import pearsonr, spearmanr

## 데이터 불러오기

In [8]:
path = './data/'

df = pd.read_csv(path+'전세가격예측프로젝트_월별데이터_총병합.csv')

In [9]:
df

,Year,Month,Region_Name,Region_Code,Building_Use,Sell_Price,Sell_BA,Sell_PPA,Sell_PPP,Sell_Count,...,JS_Count,CR,BA_CR,PPA_CR,IR,UR,LC_index,CA_index,TC_index,SDT_index
0,2012,7,강남구,11680,단독다가구,316562.50,344.92,943.75,285.48,8,...,135,3.89,19.62,22.31,3.0,3.1,74.5,81.5,78.5,102.461258
1,2012,7,강남구,11680,아파트,82549.28,81.56,1023.00,309.46,133,...,750,46.13,101.15,44.26,3.0,3.1,74.5,81.5,78.5,102.461258
2,2012,7,강남구,11680,연립다세대,28362.79,48.58,565.35,171.02,38,...,140,61.63,109.47,61.95,3.0,3.1,74.5,81.5,78.5,102.461258
3,2012,7,강남구,11680,오피스텔,25309.88,39.07,671.99,203.28,42,...,10,157.65,227.39,62.87,3.0,3.1,74.5,81.5,78.5,102.461258
4,2012,7,강동구,11740,단독다가구,103757.14,336.59,480.88,145.47,21,...,217,7.61,16.44,33.75,3.0,3.1,74.5,81.5,78.5,102.461258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12185,2022,8,중구,11140,오피스텔,33270.39,29.85,1108.02,335.18,162,...,72,74.87,104.46,74.52,2.5,2.1,109.0,109.0,110.3,87.677816
12186,2022,8,중랑구,11260,단독다가구,113917.78,221.65,517.06,156.41,81,...,271,11.79,19.67,66.34,2.5,2.1,109.0,109.0,110.3,87.677816
12187,2022,8,중랑구,11260,아파트,54521.62,58.36,989.66,299.37,74,...,414,53.66,112.94,44.39,2.5,2.1,109.0,109.0,110.3,87.677816
12188,2022,8,중랑구,11260,연립다세대,33390.06,48.04,743.72,224.98,327,...,276,72.34,78.37,95.16,2.5,2.1,109.0,109.0,110.3,87.677816
12189,2022,8,중랑구,11260,오피스텔,12275.00,23.31,531.40,160.75,18,...,36,170.66,125.61,145.74,2.5,2.1,109.0,109.0,110.3,87.677816

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12190 entries, 0 to 12189
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Year          12190 non-null  int64
 1   Month         12190 non-null  int64
 2   Region_Name   12190 non-null  object
 3   Region_Code   12190 non-null  int64
 4   Building_Use  12190 non-null  object
 5   Sell_Price    12190 non-null  float64
 6   Sell_BA       12190 non-null  float64
 7   Sell_PPA      12190 non-null  float64
 8   Sell_PPP      12190 non-null  float64
 9   Sell_Count    12190 non-null  int64
 10  JS_Price      12190 non-null  float64
 11  JS_BA         12190 non-null  float64
 12  JS_PPA        12190 non-null  float64
 13  JS_PPP        12190 non-null  float64
 14  JS_Count      12190 non-null  int64
 15  CR            12190 non-null  float64
 16  BA_CR         12190 non-null  float64
 17  PPA_CR        12190 non-null  float64
 18  IR            12190 non-null  float64
 19  UR            12190 non-null  float64
 20  LC_index      12190 non-null  float64
 21  CA_index      12190 non-null  float64
 22  TC_index      12190 non-null  float64
 23  SDT_index     12190 non-null  float64
dtypes: float64(17), int64(5), object(2)
memory usage: 2.2+ MB

## PCC

In [11]:
# 데이터 타입 변경
df['Year'] = df['Year'].astype(int)
df['Month'] = df['Month'].astype(int)
df['Sell_Count'] = df['Sell_Count'].astype(float)
df['JS_Count'] = df['JS_Count'].astype(float)

In [12]:
result_df = pd.DataFrame(columns=['Column_Name', 'PCC', 'p-value'])

# JS_Price와 다른 열 간의 PCC 및 p-value 계산 및 저장
for column in df.columns:
    if column != 'JS_Price':
        if df[column].dtype in (int, float):
            correlation, p_value = pearsonr(df['JS_Price'], df[column])
            result_df = result_df.append({'Column_Name': column, 'PCC': correlation, 'p-value': p_value}, ignore_index=True)

In [13]:
result_df.sort_values(by='PCC', ascending=False)

   Column_Name       PCC        p-value
7        JS_BA  0.703676   0.000000e+00
4     Sell_PPA  0.695960   0.000000e+00
5     Sell_PPP  0.695959   0.000000e+00
8       JS_PPA  0.655429   0.000000e+00
9       JS_PPP  0.655429   0.000000e+00
10    JS_Count  0.476762   0.000000e+00
12       BA_CR  0.424247   0.000000e+00
6   Sell_Count  0.391863   0.000000e+00
16    LC_index  0.306136  8.542035e-263
18    TC_index  0.303511  4.021770e-258
0         Year  0.302128  1.115828e-255
17    CA_index  0.301419  1.971475e-254
11          CR  0.227661  4.438028e-143
2   Sell_Price  0.223140  2.180162e-137
15          UR  0.043085   1.949173e-06
1        Month -0.002171   8.106196e-01
13      PPA_CR -0.030558   7.401041e-04
19   SDT_index -0.081371   2.298437e-19
3      Sell_BA -0.190216   1.106802e-99
14          IR -0.245833  3.068983e-167