<a href="https://colab.research.google.com/github/HSYhrae/team3_semi_project/blob/data/%EC%A2%8C%ED%91%9C_%EC%B6%94%EC%B6%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 구글 드라이브 연동

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import pandas as pd

## 데이터 불러오기

In [ ]:
jeonse_df = pd.read_csv('/content/drive/MyDrive/data/3team_project/전월세가/서울시_전세_건별통합본(23년, 건물연수 추가).csv')
jeonse_df.tail(5)

,Year,Month,Region_Code,Region_Name,KA_Code,KA_Name,LNA_Code,LNA_Name,Main_num,Sub_num,...,Num_hb,Population,IR,UR,LC_index,CA_index,TC_index,SDT_index,HSP_index,Crime_Rates
2421096,2022,11,11350,노원구,10500,상계동,1,대지,624,0,...,NaN,504265,3.25,2.3,109.7,108.9,111.8,72.039914,146.8,NaN
2421097,2022,11,11710,송파구,10200,신천동,1,대지,17,0,...,NaN,652993,3.25,2.3,109.7,108.9,111.8,72.039914,146.8,NaN
2421098,2022,11,11710,송파구,11200,오금동,1,대지,165,0,...,NaN,652993,3.25,2.3,109.7,108.9,111.8,72.039914,146.8,NaN
2421099,2022,11,11740,강동구,10300,상일동,1,대지,515,0,...,NaN,457679,3.25,2.3,109.7,108.9,111.8,72.039914,146.8,NaN
2421100,2022,11,11350,노원구,10300,공릉동,1,대지,714,0,...,NaN,504265,3.25,2.3,109.7,108.9,111.8,72.039914,146.8,NaN

In [ ]:
jeonse_df['address'].nunique()

96989

In [ ]:
unique_rows = seoul_js_data.drop_duplicates(subset='주소', keep='first')
unique_rows = unique_rows.reset_index(drop=True)
unique_rows

### Google Map API 이용 좌표 추출

In [ ]:
!pip install googlemaps

In [ ]:
import googlemaps
from datetime import datetime

apikey = '' # 해당 API 입력

def getLoc(addr):
    gmaps = googlemaps.Client(key='') # 해당 API 입력
    geocode_result = gmaps.geocode(addr)
    n_lat = geocode_result[0]['geometry']['location']['lat']
    n_lng = geocode_result[0]['geometry']['location']['lng']
    loc = {'lat':n_lat, 'lng':n_lng}
    return loc

for i in range(len(unique_rows)):
    find = unique_rows.loc[i, "address"]
    sub_lat = getLoc(find)['lat']
    sub_long = getLoc(find)['lng']
    unique_rows.loc[i, '위도'] = sub_lat
    unique_rows.loc[i, '경도'] = sub_long

# 함수 설정을 통해 구글 지오코드 서비스로 위도 경도에 대한 데이터 가져온 후
# 실거래가 데이터 프레임의 "주소" 컬럼의 주소 값들을 기반으로 위도, 경도 위치 데이터 받은 후
# "위도", "경도"에 컬럼값 위치 데이터 넣기

### 병합하기

In [ ]:
unique_rows

,Year,Month,Region_Code,Region_Name,KA_Code,KA_Name,LNA_Code,LNA_Name,Main_num,Sub_num,...,Population,IR,UR,LC_index,CA_index,TC_index,SDT_index,HSP_index,위도,경도
0,2011,4,11170,용산구,11300,원효로2가,1,대지,1,0,...,236688.0,3.00,3.7,72.5,78.4,75.3,NaN,81.2,37.537739,126.965287
1,2011,2,11440,마포구,11000,노고산동,1,대지,1,1,...,384129.0,2.75,4.5,72.3,78.2,74.5,NaN,82.0,37.556254,126.942750
2,2011,7,11650,서초구,10100,방배동,1,대지,1031,3,...,427110.0,3.25,3.3,72.7,79.5,76.5,NaN,80.1,37.478172,126.999450
3,2011,1,11620,관악구,10300,남현동,1,대지,1061,18,...,521193.0,2.75,3.8,72.0,78.2,74.2,NaN,81.2,37.474500,126.981390
4,2011,2,11440,마포구,11000,노고산동,1,대지,109,100,...,384129.0,2.75,4.5,72.3,78.2,74.5,NaN,82.0,37.552989,126.935067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96984,2022,12,11215,광진구,10100,중곡동,1,대지,18,65,...,335712.0,3.25,3.0,109.5,108.4,112.4,NaN,141.8,37.566657,127.086870
96985,2022,12,11305,강북구,10100,미아동,1,대지,258,598,...,293601.0,3.25,3.0,109.5,108.4,112.4,NaN,141.8,37.627412,127.030717
96986,2022,12,11545,금천구,10300,시흥동,1,대지,953,7,...,228373.0,3.25,3.0,109.5,108.4,112.4,NaN,141.8,37.442290,126.905779
96987,2022,12,11440,마포구,12400,연남동,1,대지,364,19,...,362719.0,3.25,3.0,109.5,108.4,112.4,NaN,141.8,37.565525,126.917845
96988,2022,12,11710,송파구,11300,거여동,1,대지,178,47,...,652993.0,3.25,3.0,109.5,108.4,112.4,NaN,141.8,37.495024,127.144055

In [ ]:
select_col = ['address', '위도', '경도']
unique_rows = unique_rows.loc[:, select_col]
unique_rows

                address         위도          경도
0           용산구 원효로2가 1  37.537739  126.965287
1          마포구 노고산동 1-1  37.556254  126.942750
2        서초구 방배동 1031-3  37.478172  126.999450
3       관악구 남현동 1061-18  37.474500  126.981390
4      마포구 노고산동 109-100  37.552989  126.935067
...                 ...        ...         ...
96984     광진구 중곡동 18-65  37.566657  127.086870
96985   강북구 미아동 258-598  37.627412  127.030717
96986     금천구 시흥동 953-7  37.442290  126.905779
96987    마포구 연남동 364-19  37.565525  126.917845
96988    송파구 거여동 178-47  37.495024  127.144055

[96989 rows x 3 columns]

In [ ]:
merged_df = pd.merge(jeonse_df, unique_rows, on=['address'], how='left')
merged_df

,Year,Month,Region_Code,Region_Name,KA_Code,KA_Name,LNA_Code,LNA_Name,Main_num,Sub_num,...,IR,UR,LC_index,CA_index,TC_index,SDT_index,HSP_index,Crime_Rates,위도,경도
0,2011,4,11170,용산구,11300,원효로2가,1,대지,1,0,...,3.00,3.7,72.5,78.4,75.3,NaN,81.2,NaN,37.537739,126.965287
1,2011,10,11170,용산구,11300,원효로2가,1,대지,1,0,...,3.25,2.9,72.9,80.0,77.1,NaN,79.4,NaN,37.537739,126.965287
2,2011,2,11440,마포구,11000,노고산동,1,대지,1,1,...,2.75,4.5,72.3,78.2,74.5,NaN,82.0,NaN,37.556254,126.942750
3,2011,11,11440,마포구,11000,노고산동,1,대지,1,1,...,3.25,2.9,72.9,79.9,77.3,NaN,78.6,NaN,37.556254,126.942750
4,2011,7,11650,서초구,10100,방배동,1,대지,1031,3,...,3.25,3.3,72.7,79.5,76.5,NaN,80.1,NaN,37.478172,126.999450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2421096,2022,11,11350,노원구,10500,상계동,1,대지,624,0,...,3.25,2.3,109.7,108.9,111.8,72.039914,146.8,NaN,37.668783,127.053725
2421097,2022,11,11710,송파구,10200,신천동,1,대지,17,0,...,3.25,2.3,109.7,108.9,111.8,72.039914,146.8,NaN,37.520536,127.106151
2421098,2022,11,11710,송파구,11200,오금동,1,대지,165,0,...,3.25,2.3,109.7,108.9,111.8,72.039914,146.8,NaN,37.497938,127.136728
2421099,2022,11,11740,강동구,10300,상일동,1,대지,515,0,...,3.25,2.3,109.7,108.9,111.8,72.039914,146.8,NaN,37.551493,127.161300
2421100,2022,11,11350,노원구,10300,공릉동,1,대지,714,0,...,3.25,2.3,109.7,108.9,111.8,72.039914,146.8,NaN,37.629880,127.071928

In [ ]:
merged_df

,Year,Month,Region_Code,Region_Name,KA_Code,KA_Name,LNA_Code,LNA_Name,Main_num,Sub_num,...,Population,IR,UR,LC_index,CA_index,TC_index,SDT_index,HSP_index,위도,경도
0,2011,4,11170,용산구,11300,원효로2가,1,대지,1,0,...,236688.0,3.00,3.7,72.5,78.4,75.3,NaN,81.2,37.537739,126.965287
1,2011,10,11170,용산구,11300,원효로2가,1,대지,1,0,...,236688.0,3.25,2.9,72.9,80.0,77.1,NaN,79.4,37.537739,126.965287
2,2011,2,11440,마포구,11000,노고산동,1,대지,1,1,...,384129.0,2.75,4.5,72.3,78.2,74.5,NaN,82.0,37.556254,126.942750
3,2011,11,11440,마포구,11000,노고산동,1,대지,1,1,...,384129.0,3.25,2.9,72.9,79.9,77.3,NaN,78.6,37.556254,126.942750
4,2011,7,11650,서초구,10100,방배동,1,대지,1031,3,...,427110.0,3.25,3.3,72.7,79.5,76.5,NaN,80.1,37.478172,126.999450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2421096,2022,11,11350,노원구,10500,상계동,1,대지,624,0,...,504265.0,3.25,2.3,109.7,108.9,111.8,NaN,146.8,37.668783,127.053725
2421097,2022,11,11710,송파구,10200,신천동,1,대지,17,0,...,652993.0,3.25,2.3,109.7,108.9,111.8,NaN,146.8,37.520536,127.106151
2421098,2022,11,11710,송파구,11200,오금동,1,대지,165,0,...,652993.0,3.25,2.3,109.7,108.9,111.8,NaN,146.8,37.497938,127.136728
2421099,2022,11,11740,강동구,10300,상일동,1,대지,515,0,...,457679.0,3.25,2.3,109.7,108.9,111.8,NaN,146.8,37.551493,127.161300
2421100,2022,11,11350,노원구,10300,공릉동,1,대지,714,0,...,504265.0,3.25,2.3,109.7,108.9,111.8,NaN,146.8,37.629880,127.071928

In [ ]:
merged_df.isnull().sum()

Year                 0
Month                0
Region_Code          0
Region_Name          0
KA_Code              0
KA_Name              0
LNA_Code             0
LNA_Name             0
Main_num             0
Sub_num              0
Floor                0
Building_Age         0
Building_Use         0
JS_Price             0
JS_BA                0
JS_PPA               0
JS_PPP               0
address              0
Num_hb          383500
Population      150868
IR               17737
UR               17737
LC_index         17737
CA_index         17737
TC_index         17737
SDT_index       482675
HSP_index        54041
위도                   0
경도                   0
dtype: int64

In [ ]:
merged_df.to_csv('/content/drive/MyDrive/data/3team_project/전월세가/서울시_전세_위도_경도_종합본.csv', encoding='utf-8', index=False)